### ISSUE TITLE
I can't see the description of my folders and items 

### ISSUE THREAD

**Issue by lorsistem** [sjarvela/mollify#4] opened 2015-02-23 20:21 UTC
Hi! It is a pleasure to communicate with you and first of all I want to thank you for such excellent file manager. I commented recently updated to version 2.6.4 and do not know why me stopped working plugin the description of items please I would like to have your help in this case since you and I tossed and turned but I can not solve.

very grateful ..

Greetings!

**Comment by lorsistem** [comment] 2015-02-23 20:27
Here I leave my screen capture
![image](https://cloud.githubusercontent.com/assets/11165554/6336397/8685d698-bb74-11e4-9ce7-166076a9bd20.png)

**Comment by sjarvela** [comment] 2015-03-04 11:48
Can you see descriptions when you open the popup (where you can edit it)?

If you can't see it there either, can you edit and give it new description?

If you do see it in popup but not in list, I suppose it is configuration issue. Description column needs to be defined in the index.html (in "file-view" / "list-view-columns", see https://github.com/sjarvela/mollify/wiki/Client-configuration-options#file-list-column-customization). So you should have "item-description" in that column list.

**Comment by lorsistem** [comment] 2015-03-04 12:47
Hello good day,

Thanks for your reply I actually told him that the settings correctly in the index.html file-view below I attached a screenshot of the configuration, another issue that I find curious and catches my attention is that when I perform a search by description there if I visualize the description in the result list but still do not see it in the main view.

![image](https://cloud.githubusercontent.com/assets/11165554/6483726/8bb2780a-c246-11e4-91cd-ef4c8577a02b.png)

![image](https://cloud.githubusercontent.com/assets/11165554/6483741/aa55f368-c246-11e4-9de0-2307105e561e.png)



Thanks really appreciate your help!

**Comment by lorsistem** [comment] 2015-03-04 12:50
sorry forget to append the configuration of index.html

![image](https://cloud.githubusercontent.com/assets/11165554/6483793/3ac67760-c247-11e4-8733-876f48603446.png)

**Comment by sjarvela** [comment] 2015-03-05 06:26
It seems you have copied all the configuration you have found, many of those are really not needed, and makes it only difficult to read the file.

Anyway, the column setup seems right, only the key "fileListColumnTitleDescription" is not valid (but should not matter).

I just cannot reproduce this on my server, and since descriptions do show when searching, it should not be up to the client configuration. What DB are you using?

**Comment by lorsistem** [comment] 2015-03-05 20:55
Hi, The BD is mysql and its installed is in local server with XAMP.

However, I updated the code and I separated each instructions (mollify.js), I saw that stop in "Return 3", then !data["item-metadata"][item.id] is null. Why is null?

Original Instruction:
/*if (!item.id || !data || !data["item-metadata"] || !data["item-metadata"][item.id].description) return ""; */

Update Instruction:
              if (!item.id ) return "1";  --- Its OK
	      if (!data ) return "2";      ---- Its OK
	      if (!data["item-metadata"][item.id]) return "3";      -->> This is the value returned.

**Comment by sjarvela** [comment] 2015-03-06 08:40
It simply means that "item-metadata" does not contain the item id. Which
means that server response does not have metadata for the selected item.

That is the key here, why is the metadata empty. But since I cannot
reproduce the error, it's hard to say.

You could
1) enable debug logging (
https://github.com/sjarvela/mollify/wiki/Backend-configuration-options#debug-mode-debug
)
2) do one page refresh with the listing that does not show descriptions
3) disable debug logging and send the log to me

**Comment by lorsistem** [comment] 2015-03-06 13:41
Hi, Good Morning

here attached the  Mollify Debug requested.

Mollify Debug

MySQLi DB: root@localhost:mollify(mollify_)EVENT HANDLER: registering '*': NotificatorHandlerEVENT HANDLER: registering 'filesystem/': EventLoggerEVENT HANDLER: registering 'session/': EventLoggerDB QUERY: select id, user_id, ip, time, last_access from mollify_session where id = '154f99f2135a07' and last_access >= 20150306133340DB QUERY: select name, value from mollify_session_data where session_id = '154f99f2135a07'DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM mollify_user left outer join mollify_user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20150306153340)DB QUERY: select id, name, description from mollify_user where id in (SELECT user_group.group_id FROM mollify_user as user, mollify_user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASCDB QUERY: UPDATE mollify_session set last_access=20150306153340 where id='154f99f2135a07'Filesystem registered: localEVENT HANDLER: registering 'filesystem/': FilesystemControllerVERSION: 2.6.4 SERVER: {MIBDIRS:C:/xampp/php/extras/mibs, MYSQL_HOME:\xampp\mysql\bin, OPENSSL_CONF:C:/xampp/apache/bin/openssl.cnf, PHP_PEAR_SYSCONF_DIR:\xampp\php, PHPRC:\xampp\php, TMP:\xampp\tmp, HTTP_X_REQUESTED_WITH:XMLHttpRequest, CONTENT_TYPE:application/json, HTTP_REFERER:http://159.234.50.3/mollify/?v=files/54c64d769599d, HTTP_COOKIE:mollify_app_session=154f99f2135a07, SystemRoot:C:\Windows, COMSPEC:C:\Windows\system32\cmd.exe, PATHEXT:.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, WINDIR:C:\Windows, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:C:/xampp/htdocs, SCRIPT_FILENAME:C:/xampp/htdocs/mollify/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:GET, QUERY_STRING:, REQUEST_URI:/mollify/backend/r.php/session/info/, SCRIPT_NAME:/mollify/backend/r.php, PATH_INFO:/session/info/, PATH_TRANSLATED:C:\xampp\htdocs\session\info\, PHP_SELF:/mollify/backend/r.php/session/info/, REQUEST_TIME_FLOAT:1425648820.603, REQUEST_TIME:1425648820}SETTINGS: {db:{type:mysql, user:root, password:, host:localhost, database:mollify, table_prefix:mollify_, charset:utf8, engine:innodb}, plugins:{Notificator:{}, FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}, TextFile:{0:txt, 1:php, 2:html}, Google:{0:pdf, 1:tiff, 2:doc}, JPlayer:{0:mp3}, FlowPlayer:{0:f4v}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}, editors:{TextFile:{0:txt}}}, EventLogging:{logged_events:{0:filesystem/, 1:session/}}}, enable_descriptions:1, enable_mail_notification:1, enable_limited_http_methods:1, enable_thumbnails:1, enable_folder_protection:, mail_notification_from:Admin, new_folder_permission_mask:493, mime_types:{avi:video/divx, wav:audio/x-wav, jpg:image/jpeg, doc:application/msword}, debug:1, debug_log:1}FEATURES: {limited_http_methods:1, change_password:, descriptions:1, user_groups:1, mail_notification:1, retrieve_url:, folder_protection:, thumbnails:1, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}FILESYSTEM: allowed_file_upload_types={}SESSION: is_active=1, user={id:1, name:admin, user_type:a, lang:, email:loreanrey@tupperware.com, expiration:, auth:}, data={auth:}AUTH: is_authenticated=1REQUEST: method=get, path={0:session, 1:info}, ip=159.234.50.123, params={}, data=SERVICE (SessionServices)DB QUERY: select id, path from mollify_item_id where path REGEXP '^.:[/\\]$'DB QUERY: SELECT f.id as id, f.type as type, uf.name as name, f.name as default_name, f.path as path FROM mollify_user_folder uf, mollify_folder f, mollify_user u WHERE (uf.user_id in (1)) AND f.id = uf.folder_id AND u.id = uf.user_id ORDER BY u.is_group ascDB QUERY: SELECT id, type, name, path FROM mollify_folder ORDER BY id ASCRESPONSE success {authenticated:1, features:{limited_http_methods:1, change_password:, descriptions:1, user_groups:1, mail_notification:1, retrieve_url:, folder_protection:, thumbnails:1, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}, resources:{custom_url:}, plugins:{Notificator:{custom:, admin:1}, FileViewerEditor:{custom:, admin:}, EventLogging:{custom:, admin:1}}, session_id:154f99f2135a07, user_id:1, username:admin, user_type:a, lang:, user_auth:pw, filesystem:{max_upload_file_size:419430400, max_upload_total_size:419430400, allowed_file_upload_types:{}, forbidden_file_upload_types:{}}, folders:{0:{id:54aafd3ad8c6a, name:03. TecnologÃ­a de InformaciÃ³n (IT), group:, parent_id:, root_id:54aafd3ad8c6a, path:}, 1:{id:54aafd9c07907, name:02. Recursos Humanos, group:, parent_id:, root_id:54aafd9c07907, path:}, 2:{id:54b69347748ca, name:09. AsesorÃ­a Administrativa y Contable (DAS), group:, parent_id:, root_id:54b69347748ca, path:}, 3:{id:54b694e81000d, name:04. Finanzas, group:, parent_id:, root_id:54b694e81000d, path:}, 4:{id:54b694e813cfe, name:01. Operaciones, group:, parent_id:, root_id:54b694e813cfe, path:}, 5:{id:54b694e81b6df, name:06. Mercadeo, group:, parent_id:, root_id:54b694e81b6df, path:}, 6:{id:54bd01365d58b, name:07. Ventas, group:, parent_id:, root_id:54bd01365d58b, path:}, 7:{id:54d0cbd95bc3b, name:10. Seguridad, group:, parent_id:, root_id:54d0cbd95bc3b, path:}}, roots:{0:{id:54aafd3ad8c6a, name:03. TecnologÃ­a de InformaciÃ³n (IT), group:, parent_id:, root_id:54aafd3ad8c6a, path:}, 1:{id:54aafd9c07907, name:02. Recursos Humanos, group:, parent_id:, root_id:54aafd9c07907, path:}, 2:{id:54b69347748ca, name:09. AsesorÃ­a Administrativa y Contable (DAS), group:, parent_id:, root_id:54b69347748ca, path:}, 3:{id:54b694e81000d, name:04. Finanzas, group:, parent_id:, root_id:54b694e81000d, path:}, 4:{id:54b694e813cfe, name:01. Operaciones, group:, parent_id:, root_id:54b694e813cfe, path:}, 5:{id:54b694e81b6df, name:06. Mercadeo, group:, parent_id:, root_id:54b694e81b6df, path:}, 6:{id:54bd01365d58b, name:07. Ventas, group:, parent_id:, root_id:54bd01365d58b, path:}, 7:{id:54d0cbd95bc3b, name:10. Seguridad, group:, parent_id:, root_id:54d0cbd95bc3b, path:}}, permissions:{change_password:1}, permission_types:{keys:{generic:{0:change_password}, filesystem:{0:filesystem_item_access, 1:edit_description}, all:{0:change_password, 1:filesystem_item_access, 2:edit_description}}, values:{change_password:, filesystem_item_access:{0:n, 1:r, 2:rw, 3:rwd}, edit_description:}}, version:2.6.4, revision:16}MySQLi DB: root@localhost:mollify(mollify_)EVENT HANDLER: registering '*': NotificatorHandlerEVENT HANDLER: registering 'filesystem/': EventLoggerEVENT HANDLER: registering 'session/': EventLoggerDB QUERY: select id, user_id, ip, time, last_access from mollify_session where id = '154f99f2135a07' and last_access >= 20150306133341DB QUERY: select name, value from mollify_session_data where session_id = '154f99f2135a07'DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM mollify_user left outer join mollify_user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20150306153341)DB QUERY: select id, name, description from mollify_user where id in (SELECT user_group.group_id FROM mollify_user as user, mollify_user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASCDB QUERY: UPDATE mollify_session set last_access=20150306153341 where id='154f99f2135a07'Filesystem registered: localEVENT HANDLER: registering 'filesystem/': FilesystemControllerVERSION: 2.6.4 SERVER: {MIBDIRS:C:/xampp/php/extras/mibs, MYSQL_HOME:\xampp\mysql\bin, OPENSSL_CONF:C:/xampp/apache/bin/openssl.cnf, PHP_PEAR_SYSCONF_DIR:\xampp\php, PHPRC:\xampp\php, TMP:\xampp\tmp, CONTENT_LENGTH:100, HTTP_ORIGIN:http://159.234.50.3, HTTP_MOLLIFY_SESSION_ID:154f99f2135a07, CONTENT_TYPE:application/json, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_MOLLIFY_HTTP_METHOD:POST, HTTP_REFERER:http://159.234.50.3/mollify/?v=files/54c64d769599d, HTTP_COOKIE:mollify_app_session=154f99f2135a07, SystemRoot:C:\Windows, COMSPEC:C:\Windows\system32\cmd.exe, PATHEXT:.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, WINDIR:C:\Windows, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:C:/xampp/htdocs, SCRIPT_FILENAME:C:/xampp/htdocs/mollify/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:POST, QUERY_STRING:h=1, REQUEST_URI:/mollify/backend/r.php/filesystem/54c64d769599d/info/?h=1, SCRIPT_NAME:/mollify/backend/r.php, PATH_INFO:/filesystem/54c64d769599d/info/, PATH_TRANSLATED:C:\xampp\htdocs\filesystem\54c64d769599d\info\, PHP_SELF:/mollify/backend/r.php/filesystem/54c64d769599d/info/, REQUEST_TIME_FLOAT:1425648820.962, REQUEST_TIME:1425648820}SETTINGS: {db:{type:mysql, user:root, password:, host:localhost, database:mollify, table_prefix:mollify_, charset:utf8, engine:innodb}, plugins:{Notificator:{}, FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}, TextFile:{0:txt, 1:php, 2:html}, Google:{0:pdf, 1:tiff, 2:doc}, JPlayer:{0:mp3}, FlowPlayer:{0:f4v}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}, editors:{TextFile:{0:txt}}}, EventLogging:{logged_events:{0:filesystem/, 1:session/}}}, enable_descriptions:1, enable_mail_notification:1, enable_limited_http_methods:1, enable_thumbnails:1, enable_folder_protection:, mail_notification_from:Admin, new_folder_permission_mask:493, mime_types:{avi:video/divx, wav:audio/x-wav, jpg:image/jpeg, doc:applfy_item_id where path='6:\\Sistema de GestiÃ³n de Calidad\\01. ISO 9001-2008\\'DB QUERY: select id from mollify_item_id where path='6:\\Sistema de GestiÃ³n de Calidad\\01. ISO 9001-2008\\1.2 DocumentaciÃ³n\\'DB QUERY: select id from mollify_item_id where path='6:\\Sistema de GestiÃ³n de Calidad\\01. ISO 9001-2008\\1.2 DocumentaciÃ³n\\1.2.2 Nivel II\\'RESPONSE success {folder:{id:54c64d769599d, root_id:54b694e813cfe, parent_id:54c64d65b9429, name:P4.2.3 Control de Documentos, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\1.2.2 Nivel II\1.2.2.1 Procedimientos Obligatorios\P4.2.3 Control de Documentos\, is_file:}, files:{0:{id:54d27209bd7b3, root_id:54b694e813cfe, parent_id:54c64d769599d, name:F-I 4.2.3-04.xls, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\1.2.2 Nivel II\1.2.2.1 Procedimientos Obligatorios\P4.2.3 Control de Documentos\F-I 4.2.3-04.xls, is_file:1, size:75776, extension:xls}, 1:{id:54d271a69e834, root_id:54b694e813cfe, parent_id:54c64d769599d, name:Productos volÃºmes DOSP.xlsx, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\1.2.2 Nivel II\1.2.2.1 Procedimientos Obligatorios\P4.2.3 Control de Documentos\Productos volÃºmes DOSP.xlsx, is_file:1, size:213342, extension:xlsx}}, folders:{}, permissions:{filesystem_item_access:rwd, edit_description:1}, data:{core-file-modified:{54d27209bd7b3:20150224160556, 54d271a69e834:20150204212318}, item-metadata:{}, parent-metadata:{description:Formatos}}, hierarchy:{0:{id:54b694e813cfe, root_id:54b694e813cfe, parent_id:, name:01. Operaciones, path:, is_file:}, 1:{id:54c117c37ae65, root_id:54b694e813cfe, parent_id:54b694e813cfe, name:Sistema de GestiÃ³n de Calidad, path:Sistema de GestiÃ³n de Calidad\, is_file:}, 2:{id:54c11820f015f, root_id:54b694e813cfe, parent_id:54c117c37ae65, name:01. ISO 9001-2008, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\, is_file:}, 3:{id:54c648d5b15e1, root_id:54b694e813cfe, parent_id:54c11820f015f, name:1.2 DocumentaciÃ³n, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\, is_file:}, 4:{id:54c64cf4ed375, root_id:54b694e813cfe, parent_id:54c648d5b15e1, name:1.2.2 Nivel II, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\1.2.2 Nivel II\, is_file:}, 5:{id:54c64d65b9429, root_id:54b694e813cfe, parent_id:54c64cf4ed375, name:1.2.2.1 Procedimientos Obligatorios, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\1.2.2 Nivel II\1.2.2.1 Procedimientos Obligatorios\, is_file:}, 6:{id:54c64d769599d, root_id:54b694e813cfe, parent_id:54c64d65b9429, name:P4.2.3 Control de Documentos, path:Sistema de GestiÃ³n de Calidad\01. ISO 9001-2008\1.2 DocumentaciÃ³n\1.2.2 Nivel II\1.2.2.1 Procedimientos Obligatorios\P4.2.3 Control de Documentos\, is_file:}}}

Thanks
Regards..

**Comment by sjarvela** [comment] 2015-03-09 10:01
This is a bit difficult to solve, it's like the log is truncated somehow.

I can see from the log
a) response has empty item-metadata -section (=metadata is not retrieved for the child items)
b) response does have parent metadata description (=parent metadata is retrieved)

But log does not have DB query for either, and some rows are truncated, so this does not yet help that much.

Could you send me the entire log file?

**Comment by lorsistem** [comment] 2015-03-10 19:25
Hi!
Dear sjarvela.

Here attached the log request.

Thank's

2015-03-09 5:31 GMT-04:30 sjarvela <notifications@github.com>:

> This is a bit difficult to solve, it's like the log is truncated somehow.
>
> I can see from the log
> a) response has empty item-metadata -section (=metadata is not retrieved
> for the child items)
> b) response does have parent metadata description (=parent metadata is
> retrieved)
>
> But log does not have DB query for either, and some rows are truncated, so
> this does not yet help that much.
>
> Could you send me the entire log file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sjarvela/mollify/issues/4#issuecomment-77826713>.
>



-- 

*Atte. Ing. Lorean Rey*

*Este mensaje y sus adjuntos pueden contener información privilegiada o
confidencial para uso exclusivo de la persona o entidad destino. si usted
no es el destinatario indicado, le notificamos que la lectura, utilización,
divulgación y/o copia sin autorización del mismo podrá estar prohibida por
la legislación vigente. si usted recibirá este mensaje por error, por favor
comuniquelo a través de esta vía y proceda a su destrucción.*

Mollify Debug

MySQLi DB: root@localhost:mollify(mollify_)EVENT HANDLER: registering '*': NotificatorHandlerEVENT HANDLER: registering 'filesystem/': EventLoggerEVENT HANDLER: registering 'session/': EventLoggerDB QUERY: select id, user_id, ip, time, last_access from mollify_session where id = '154ff3f7b117c4' and last_access >= 20150310190841DB QUERY: select name, value from mollify_session_data where session_id = '154ff3f7b117c4'DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM mollify_user left outer join mollify_user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20150310210841)DB QUERY: select id, name, description from mollify_user where id in (SELECT user_group.group_id FROM mollify_user as user, mollify_user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASCDB QUERY: UPDATE mollify_session set last_access=20150310210841 where id='154ff3f7b117c4'Filesystem registered: localEVENT HANDLER: registering 'filesystem/': FilesystemControllerVERSION: 2.6.6 SERVER: {MIBDIRS:C:/xampp/php/extras/mibs, MYSQL_HOME:\xampp\mysql\bin, OPENSSL_CONF:C:/xampp/apache/bin/openssl.cnf, PHP_PEAR_SYSCONF_DIR:\xampp\php, PHPRC:\xampp\php, TMP:\xampp\tmp, HTTP_CACHE_CONTROL:max-age=0, HTTP_X_REQUESTED_WITH:XMLHttpRequest, CONTENT_TYPE:application/json, HTTP_REFERER:http://159.234.50.3/mollify/?v=files/54b694e813cfe, HTTP_COOKIE:mollify_app_session=154ff3f7b117c4, SystemRoot:C:\Windows, COMSPEC:C:\Windows\system32\cmd.exe, PATHEXT:.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, WINDIR:C:\Windows, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:C:/xampp/htdocs, SCRIPT_FILENAME:C:/xampp/htdocs/mollify/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:GET, QUERY_STRING:, REQUEST_URI:/mollify/backend/r.php/session/info/, SCRIPT_NAME:/mollify/backend/r.php, PATH_INFO:/session/info/, PATH_TRANSLATED:C:\xampp\htdocs\session\info\, PHP_SELF:/mollify/backend/r.php/session/info/, REQUEST_TIME_FLOAT:1426014521.126, REQUEST_TIME:1426014521}SETTINGS: {db:{type:mysql, user:root, password:, host:localhost, database:mollify, table_prefix:mollify_, charset:utf8, engine:innodb}, plugins:{Notificator:{}, FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}, TextFile:{0:txt, 1:php, 2:html}, Google:{0:pdf, 1:tiff, 2:doc}, JPlayer:{0:mp3}, FlowPlayer:{0:f4v}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}, editors:{TextFile:{0:txt}}}, EventLogging:{logged_events:{0:filesystem/, 1:session/}}}, enable_descriptions:1, enable_mail_notification:1, enable_limited_http_methods:1, enable_thumbnails:1, enable_folder_protection:, mail_notification_from:Admin, new_folder_permission_mask:511, mime_types:{avi:video/divx, wav:audio/x-wav, jpg:image/jpeg, doc:application/msword}, debug:1, debug_log:1}FEATURES: {limited_http_methods:1, change_password:1, descriptions:1, user_groups:1, mail_notification:1, retrieve_url:, folder_protection:, thumbnails:1, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}FILESYSTEM: allowed_file_upload_types={}SESSION: is_active=1, user={id:1, name:admin, user_type:a, lang:, email:loreanrey@tupperware.com, expiration:, auth:}, data={auth:}AUTH: is_authenticated=1REQUEST: method=get, path={0:session, 1:info}, ip=159.234.50.123, params={}, data=SERVICE (SessionServices)DB QUERY: select id, path from mollify_item_id where path REGEXP '^.:[/\\]$'DB QUERY: SELECT f.id as id, f.type as type, uf.name as name, f.name as default_name, f.path as path FROM mollify_user_folder uf, mollify_folder f, mollify_user u WHERE (uf.user_id in (1)) AND f.id = uf.folder_id AND u.id = uf.user_id ORDER BY u.is_group ascDB QUERY: SELECT id, type, name, path FROM mollify_folder ORDER BY id ASCRESPONSE success {authenticated:1, features:{limited_http_methods:1, change_password:1, descriptions:1, user_groups:1, mail_notification:1, retrieve_url:, folder_protection:, thumbnails:1, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}, resources:{custom_url:}, plugins:{Notificator:{custom:, admin:1}, FileViewerEditor:{custom:, admin:}, EventLogging:{custom:, admin:1}}, session_id:154ff3f7b117c4, user_id:1, username:admin, user_type:a, lang:, user_auth:pw, filesystem:{max_upload_file_size:419430400, max_upload_total_size:419430400, allowed_file_upload_types:{}, forbidden_file_upload_types:{}}, folders:{0:{id:54aafd3ad8c6a, name:03. TecnologÃ­a de InformaciÃ³n (IT), group:, parent_id:, root_id:54aafd3ad8c6a, path:}, 1:{id:54aafd9c07907, name:02. Recursos Humanos, group:, parent_id:, root_id:54aafd9c07907, path:}, 2:{id:54b69347748ca, name:09. AsesorÃ­a Administrativa y Contable (DAS), group:, parent_id:, root_id:54b69347748ca, path:}, 3:{id:54b694e81000d, name:04. Finanzas, group:, parent_id:, root_id:54b694e81000d, path:}, 4:{id:54b694e813cfe, name:01. Operaciones, group:, parent_id:, root_id:54b694e813cfe, path:}, 5:{id:54b694e81b6df, name:06. Mercadeo, group:, parent_id:, root_id:54b694e81b6df, path:}, 6:{id:54bd01365d58b, name:07. Ventas, group:, parent_id:, root_id:54bd01365d58b, path:}, 7:{id:54d0cbd95bc3b, name:10. Seguridad, group:, parent_id:, root_id:54d0cbd95bc3b, path:}}, roots:{0:{id:54aafd3ad8c6a, name:03. TecnologÃ­a de InformaciÃ³n (IT), group:, parent_id:, root_id:54aafd3ad8c6a, path:}, 1:{id:54aafd9c07907, name:02. Recursos Humanos, group:, parent_id:, root_id:54aafd9c07907, path:}, 2:{id:54b69347748ca, name:09. AsesorÃ­a Administrativa y Contable (DAS), group:, parent_id:, root_id:54b69347748ca, path:}, 3:{id:54b694e81000d, name:04. Finanzas, group:, parent_id:, root_id:54b694e81000d, path:}, 4:{id:54b694e813cfe, name:01. Operaciones, group:, parent_id:, root_id:54b694e813cfe, path:}, 5:{id:54b694e81b6df, name:06. Mercadeo, group:, parent_id:, root_id:54b694e81b6df, path:}, 6:{id:54bd01365d58b, name:07. Ventas, group:, parent_id:, root_id:54bd01365d58b, path:}, 7:{id:54d0cbd95bc3b, name:10. Seguridad, group:, parent_id:, root_id:54d0cbd95bc3b, path:}}, permissions:{change_password:1}, permission_types:{keys:{generic:{0:change_password}, filesystem:{0:filesystem_item_access, 1:edit_description}, all:{0:change_password, 1:filesystem_item_access, 2:edit_description}}, values:{change_password:, filesystem_item_access:{0:n, 1:r, 2:rw, 3:rwd}, edit_description:}}, version:2.6.6, revision:18}MySQLi DB: root@localhost:mollify(mollify_)EVENT HANDLER: registering '*': NotificatorHandlerEVENT HANDLER: registering 'filesystem/': EventLoggerEVENT HANDLER: registering 'session/': EventLoggerDB QUERY: select id, user_id, ip, time, last_access from mollify_session where id = '154ff3f7b117c4' and last_access >= 20150310190841DB QUERY: select name, value from mollify_session_data where session_id = '154ff3f7b117c4'DB QUERY: SELECT id, name, user_type, lang, email, expiration, ua.type as auth FROM mollify_user left outer join mollify_user_auth ua on id=ua.user_id WHERE id='1' AND (expiration is null or expiration > 20150310210841)DB QUERY: select id, name, description from mollify_user where id in (SELECT user_group.group_id FROM mollify_user as user, mollify_user_group as user_group where user_group.user_id = user.id and user.id = '1') ORDER BY id ASCDB QUERY: UPDATE mollify_session set last_access=20150310210841 where id='154ff3f7b117c4'Filesystem registered: localEVENT HANDLER: registering 'filesystem/': FilesystemControllerVERSION: 2.6.6 SERVER: {MIBDIRS:C:/xampp/php/extras/mibs, MYSQL_HOME:\xampp\mysql\bin, OPENSSL_CONF:C:/xampp/apache/bin/openssl.cnf, PHP_PEAR_SYSCONF_DIR:\xampp\php, PHPRC:\xampp\php, TMP:\xampp\tmp, CONTENT_LENGTH:100, HTTP_ORIGIN:http://159.234.50.3, HTTP_MOLLIFY_SESSION_ID:154ff3f7b117c4, CONTENT_TYPE:application/json, HTTP_X_REQUESTED_WITH:XMLHttpRequest, HTTP_MOLLIFY_HTTP_METHOD:POST, HTTP_REFERER:http://159.234.50.3/mollify/?v=files/54b694e813cfe, HTTP_COOKIE:mollify_app_session=154ff3f7b117c4, SystemRoot:C:\Windows, COMSPEC:C:\Windows\system32\cmd.exe, PATHEXT:.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, WINDIR:C:\Windows, REQUEST_SCHEME:http, CONTEXT_PREFIX:, CONTEXT_DOCUMENT_ROOT:C:/xampp/htdocs, SCRIPT_FILENAME:C:/xampp/htdocs/mollify/backend/r.php, SERVER_PROTOCOL:HTTP/1.1, REQUEST_METHOD:POST, QUERY_STRING:h=1, REQUEST_URI:/mollify/backend/r.php/filesystem/54b694e813cfe/info/?h=1, SCRIPT_NAME:/mollify/backend/r.php, PATH_INFO:/filesystem/54b694e813cfe/info/, PATH_TRANSLATED:C:\xampp\htdocs\filesystem\54b694e813cfe\info\, PHP_SELF:/mollify/backend/r.php/filesystem/54b694e813cfe/info/, REQUEST_TIME_FLOAT:1426014521.47, REQUEST_TIME:1426014521}SETTINGS: {db:{type:mysql, user:root, password:, host:localhost, database:mollify, table_prefix:mollify_, charset:utf8, engine:innodb}, plugins:{Notificator:{}, FileViewerEditor:{viewers:{Image:{0:gif, 1:png, 2:jpg}, TextFile:{0:txt, 1:php, 2:html}, Google:{0:pdf, 1:tiff, 2:doc}, JPlayer:{0:mp3}, FlowPlayer:{0:f4v}}, previewers:{Image:{0:gif, 1:png, 2:jpg}}, editors:{TextFile:{0:txt}}}, EventLogging:{logged_events:{0:filesystem/, 1:session/}}}, enable_descriptions:1, enable_mail_notification:1, enable_limited_http_methods:1, enable_thumbnails:1, enable_folder_protection:, mail_notification_from:Admin, new_folder_permission_mask:511, mime_types:{avi:video/divx, wav:audio/x-wav, jpg:image/jpeg, doc:application/msword}, debug:1, debug_log:1}FEATURES: {limited_http_methods:1, change_password:1, descriptions:1, user_groups:1, mail_notification:1, retrieve_url:, folder_protection:, thumbnails:1, guest_mode:, file_view:1, file_preview:1, file_edit:1, event_logging:1}FILESYSTEM: allowed_file_upload_types={}SESSION: is_active=1, user={id:1, name:admin, user_type:a, lang:, email:loreanrey@tupperware.com, expiration:, auth:}, data={auth:}AUTH: is_authenticated=1REQUEST: method=post, path={0:filesystem, 1:54b694e813cfe, 2:info}, ip=159.234.50.123, params={h:1}, data={data:{parent-metadata:{}, core-file-modified:{}, plugin-comment-count:{}, item-metadata:{}}}SERVICE (FilesystemServices)DB QUERY: select path from mollify_item_id where id='54b694e813cfe'DB QUERY: SELECT id, type, name, path FROM mollify_folder where id='6'DB QUERY: select id from mollify_item_id where path='6:\\'DB QUERY: select id, path from mollify_item_id where path REGEXP '^6:\\\\[^/\\]+[/\\]?$'DB QUERY: SELECT item_id, md_key, md_value FROM mollify_metadata WHERE item_id in (select id from mollify_item_id where path like '6:\\%') order by item_id ascDB QUERY: SELECT md_key, md_value FROM mollify_metadata WHERE item_id = '54b694e813cfe'RESPONSE success {folder:{id:54b694e813cfe, root_id:54b694e813cfe, parent_id:, name:01. Operaciones, path:, is_file:}, files:{}, folders:{0:{id:54fdc2d536486, root_id:54b694e813cfe, parent_id:54b694e813cfe, name:BoletÃ­n Informativo SGOP, path:BoletÃ­n Informativo SGOP\, is_file:}, 1:{id:54c117c37ae65, root_id:54b694e813cfe, parent_id:54b694e813cfe, name:Sistema de GestiÃ³n de Calidad, path:Sistema de GestiÃ³n de Calidad\, is_file:}}, permissions:{filesystem_item_access:rwd, edit_description:1}, data:{core-file-modified:{54fdc2d536486:20150309225143, 54c117c37ae65:20150309231100}, item-metadata:{}, parent-metadata:{description:ISO 9001:2008}}, hierarchy:{0:{id:54b694e813cfe, root_id:54b694e813cfe, parent_id:, name:01. Operaciones, path:, is_file:}}}

**Comment by sjarvela** [comment] 2015-03-13 09:34
I can see the DB query there, but for some reason the result is empty. I cannot solve this without gaining access to the site and DB.

But since it seems you are running this on Windows server, it might very well be due to the different path delimiter. There is active issue #12 that might help with this (although you don't have error from the query).

**Comment by sjarvela** [comment] 2015-04-09 06:37
Forgot to close this, as #12 should fix this. And project development is continued with https://github.com/sjarvela/kloudspeaker

**Closed by sjarvela** 2015-04-09 06:37 UTC
